name: Label PR on Comment

on:
  issue_comment:
    types: [created]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/bug')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Label PR
        run: |
          pip install -r requirements.txt
          python label_pr.py
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
