name: Label PR on Comment

on: issue_comment

jobs:
  pr_commented:
    name: PR Comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  label-pr:
    permissions: write-all
    name: Label PR
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/bug') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Label PR
        run: |
          pip install -r requirements.txt
          python label_pr.py
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
