name: Secrets Demo

on: [ push ]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          print(os.getenv('MY_SECRET')
        shell: python
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
